# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\AddMediaDialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_AddMediaDialog(object):
    def setupUi(self, AddMediaDialog):
        AddMediaDialog.setObjectName(_fromUtf8("AddMediaDialog"))
        AddMediaDialog.resize(853, 445)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("rsc/icon/mainWindow_icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AddMediaDialog.setWindowIcon(icon)
        self.MediaLocationGroupBox = QtGui.QGroupBox(AddMediaDialog)
        self.MediaLocationGroupBox.setGeometry(QtCore.QRect(30, 30, 421, 301))
        self.MediaLocationGroupBox.setObjectName(_fromUtf8("MediaLocationGroupBox"))
        self.layoutWidget = QtGui.QWidget(self.MediaLocationGroupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 171, 341, 111))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout_4 = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.InterfaceChoseDisplayStatic = QtGui.QLabel(self.layoutWidget)
        self.InterfaceChoseDisplayStatic.setObjectName(_fromUtf8("InterfaceChoseDisplayStatic"))
        self.gridLayout_4.addWidget(self.InterfaceChoseDisplayStatic, 0, 0, 1, 1)
        self.ChooseInterfaceBtn = QtGui.QPushButton(self.layoutWidget)
        self.ChooseInterfaceBtn.setObjectName(_fromUtf8("ChooseInterfaceBtn"))
        self.gridLayout_4.addWidget(self.ChooseInterfaceBtn, 0, 1, 1, 1)
        self.InterfaceChoseDisplayText = QtGui.QTextEdit(self.layoutWidget)
        self.InterfaceChoseDisplayText.setObjectName(_fromUtf8("InterfaceChoseDisplayText"))
        self.gridLayout_4.addWidget(self.InterfaceChoseDisplayText, 1, 0, 1, 2)
        self.LocalMediaRadioBtn = QtGui.QRadioButton(self.MediaLocationGroupBox)
        self.LocalMediaRadioBtn.setGeometry(QtCore.QRect(43, 151, 95, 16))
        self.LocalMediaRadioBtn.setObjectName(_fromUtf8("LocalMediaRadioBtn"))
        self.RemoteMediaRadioBtn = QtGui.QRadioButton(self.MediaLocationGroupBox)
        self.RemoteMediaRadioBtn.setGeometry(QtCore.QRect(44, 51, 95, 16))
        self.RemoteMediaRadioBtn.setObjectName(_fromUtf8("RemoteMediaRadioBtn"))
        self.widget = QtGui.QWidget(self.MediaLocationGroupBox)
        self.widget.setGeometry(QtCore.QRect(146, 10, 225, 131))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.widget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.RemoteCapIpStatic = QtGui.QLabel(self.widget)
        self.RemoteCapIpStatic.setObjectName(_fromUtf8("RemoteCapIpStatic"))
        self.gridLayout_2.addWidget(self.RemoteCapIpStatic, 0, 0, 1, 1)
        self.RemoteCapIpEdit = QtGui.QLineEdit(self.widget)
        self.RemoteCapIpEdit.setObjectName(_fromUtf8("RemoteCapIpEdit"))
        self.gridLayout_2.addWidget(self.RemoteCapIpEdit, 0, 1, 1, 2)
        self.RemoteCapPortStatic = QtGui.QLabel(self.widget)
        self.RemoteCapPortStatic.setObjectName(_fromUtf8("RemoteCapPortStatic"))
        self.gridLayout_2.addWidget(self.RemoteCapPortStatic, 1, 0, 1, 2)
        self.RemoteCapPortEdit = QtGui.QLineEdit(self.widget)
        self.RemoteCapPortEdit.setObjectName(_fromUtf8("RemoteCapPortEdit"))
        self.gridLayout_2.addWidget(self.RemoteCapPortEdit, 1, 2, 1, 1)
        self.RmtUsrNameStatic = QtGui.QLabel(self.widget)
        self.RmtUsrNameStatic.setObjectName(_fromUtf8("RmtUsrNameStatic"))
        self.gridLayout_2.addWidget(self.RmtUsrNameStatic, 2, 0, 1, 2)
        self.RmtUsrNameEdit = QtGui.QLineEdit(self.widget)
        self.RmtUsrNameEdit.setObjectName(_fromUtf8("RmtUsrNameEdit"))
        self.gridLayout_2.addWidget(self.RmtUsrNameEdit, 2, 2, 1, 1)
        self.RmtPwdStatic = QtGui.QLabel(self.widget)
        self.RmtPwdStatic.setObjectName(_fromUtf8("RmtPwdStatic"))
        self.gridLayout_2.addWidget(self.RmtPwdStatic, 3, 0, 1, 2)
        self.RmtPwdEdit = QtGui.QLineEdit(self.widget)
        self.RmtPwdEdit.setObjectName(_fromUtf8("RmtPwdEdit"))
        self.gridLayout_2.addWidget(self.RmtPwdEdit, 3, 2, 1, 1)
        self.groupBox = QtGui.QGroupBox(AddMediaDialog)
        self.groupBox.setGeometry(QtCore.QRect(460, 30, 371, 301))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.layoutWidget1 = QtGui.QWidget(self.groupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(40, 27, 261, 241))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget1)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.RtspPortStatic = QtGui.QLabel(self.layoutWidget1)
        self.RtspPortStatic.setObjectName(_fromUtf8("RtspPortStatic"))
        self.gridLayout.addWidget(self.RtspPortStatic, 0, 0, 1, 1)
        self.RtspPortEdit = QtGui.QLineEdit(self.layoutWidget1)
        self.RtspPortEdit.setObjectName(_fromUtf8("RtspPortEdit"))
        self.gridLayout.addWidget(self.RtspPortEdit, 0, 1, 1, 2)
        self.UdpPortBaseStatic = QtGui.QLabel(self.layoutWidget1)
        self.UdpPortBaseStatic.setObjectName(_fromUtf8("UdpPortBaseStatic"))
        self.gridLayout.addWidget(self.UdpPortBaseStatic, 1, 0, 1, 2)
        self.UdpPortBaseEdit = QtGui.QLineEdit(self.layoutWidget1)
        self.UdpPortBaseEdit.setObjectName(_fromUtf8("UdpPortBaseEdit"))
        self.gridLayout.addWidget(self.UdpPortBaseEdit, 1, 2, 1, 1)
        self.UdpPortNumStatic = QtGui.QLabel(self.layoutWidget1)
        self.UdpPortNumStatic.setObjectName(_fromUtf8("UdpPortNumStatic"))
        self.gridLayout.addWidget(self.UdpPortNumStatic, 2, 0, 1, 2)
        self.UdpPortNumEdit = QtGui.QLineEdit(self.layoutWidget1)
        self.UdpPortNumEdit.setObjectName(_fromUtf8("UdpPortNumEdit"))
        self.gridLayout.addWidget(self.UdpPortNumEdit, 2, 2, 1, 1)
        self.RtspRecvPortBaseStatic = QtGui.QLabel(self.layoutWidget1)
        self.RtspRecvPortBaseStatic.setObjectName(_fromUtf8("RtspRecvPortBaseStatic"))
        self.gridLayout.addWidget(self.RtspRecvPortBaseStatic, 3, 0, 1, 2)
        self.RtspRecvPortBaseEdit = QtGui.QLineEdit(self.layoutWidget1)
        self.RtspRecvPortBaseEdit.setObjectName(_fromUtf8("RtspRecvPortBaseEdit"))
        self.gridLayout.addWidget(self.RtspRecvPortBaseEdit, 3, 2, 1, 1)
        self.RtspRecvPortNumStatic = QtGui.QLabel(self.layoutWidget1)
        self.RtspRecvPortNumStatic.setObjectName(_fromUtf8("RtspRecvPortNumStatic"))
        self.gridLayout.addWidget(self.RtspRecvPortNumStatic, 4, 0, 1, 2)
        self.RtspRecvPortNumEdit = QtGui.QLineEdit(self.layoutWidget1)
        self.RtspRecvPortNumEdit.setObjectName(_fromUtf8("RtspRecvPortNumEdit"))
        self.gridLayout.addWidget(self.RtspRecvPortNumEdit, 4, 2, 1, 1)
        self.RtspSendPortBaseStatic = QtGui.QLabel(self.layoutWidget1)
        self.RtspSendPortBaseStatic.setObjectName(_fromUtf8("RtspSendPortBaseStatic"))
        self.gridLayout.addWidget(self.RtspSendPortBaseStatic, 5, 0, 1, 2)
        self.RtspSendPortBaseEdit = QtGui.QLineEdit(self.layoutWidget1)
        self.RtspSendPortBaseEdit.setObjectName(_fromUtf8("RtspSendPortBaseEdit"))
        self.gridLayout.addWidget(self.RtspSendPortBaseEdit, 5, 2, 1, 1)
        self.RtspSendPortNumStatic = QtGui.QLabel(self.layoutWidget1)
        self.RtspSendPortNumStatic.setObjectName(_fromUtf8("RtspSendPortNumStatic"))
        self.gridLayout.addWidget(self.RtspSendPortNumStatic, 6, 0, 1, 2)
        self.RtspSendPortNumEdit = QtGui.QLineEdit(self.layoutWidget1)
        self.RtspSendPortNumEdit.setObjectName(_fromUtf8("RtspSendPortNumEdit"))
        self.gridLayout.addWidget(self.RtspSendPortNumEdit, 6, 2, 1, 1)
        self.layoutWidget2 = QtGui.QWidget(AddMediaDialog)
        self.layoutWidget2.setGeometry(QtCore.QRect(120, 344, 571, 41))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.OkBtn = QtGui.QPushButton(self.layoutWidget2)
        self.OkBtn.setObjectName(_fromUtf8("OkBtn"))
        self.horizontalLayout.addWidget(self.OkBtn)
        self.NoBtn = QtGui.QPushButton(self.layoutWidget2)
        self.NoBtn.setObjectName(_fromUtf8("NoBtn"))
        self.horizontalLayout.addWidget(self.NoBtn)

        self.retranslateUi(AddMediaDialog)
        QtCore.QMetaObject.connectSlotsByName(AddMediaDialog)

    def retranslateUi(self, AddMediaDialog):
        AddMediaDialog.setWindowTitle(_translate("AddMediaDialog", "AddMedia", None))
        self.MediaLocationGroupBox.setTitle(_translate("AddMediaDialog", "媒体网关位置", None))
        self.InterfaceChoseDisplayStatic.setText(_translate("AddMediaDialog", "网络适配器：", None))
        self.ChooseInterfaceBtn.setText(_translate("AddMediaDialog", "选择网络适配器", None))
        self.LocalMediaRadioBtn.setText(_translate("AddMediaDialog", "本机媒体网关", None))
        self.RemoteMediaRadioBtn.setText(_translate("AddMediaDialog", "远程媒体网关", None))
        self.RemoteCapIpStatic.setText(_translate("AddMediaDialog", "IP地址：", None))
        self.RemoteCapPortStatic.setText(_translate("AddMediaDialog", "远程抓包端口：", None))
        self.RmtUsrNameStatic.setText(_translate("AddMediaDialog", "远程用户名：", None))
        self.RmtPwdStatic.setText(_translate("AddMediaDialog", "远程密码：", None))
        self.groupBox.setTitle(_translate("AddMediaDialog", "媒体网关使用端口信息", None))
        self.RtspPortStatic.setText(_translate("AddMediaDialog", "RTSP端口：", None))
        self.UdpPortBaseStatic.setText(_translate("AddMediaDialog", "UDP传输流开始端口：", None))
        self.UdpPortNumStatic.setText(_translate("AddMediaDialog", "UDP传输流端口数目：", None))
        self.RtspRecvPortBaseStatic.setText(_translate("AddMediaDialog", "RTSP接收流开始端口：", None))
        self.RtspRecvPortNumStatic.setText(_translate("AddMediaDialog", "RTSP接收流端口数目：", None))
        self.RtspSendPortBaseStatic.setText(_translate("AddMediaDialog", "RTSP发送流开始端口：", None))
        self.RtspSendPortNumStatic.setText(_translate("AddMediaDialog", "RTSP发送流端口数目：", None))
        self.OkBtn.setText(_translate("AddMediaDialog", "确认", None))
        self.NoBtn.setText(_translate("AddMediaDialog", "取消", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    AddMediaDialog = QtGui.QDialog()
    ui = Ui_AddMediaDialog()
    ui.setupUi(AddMediaDialog)
    AddMediaDialog.show()
    sys.exit(app.exec_())

